# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientofperformancelogger',
            name='COP_HP',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
