# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20150708_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor1CIU1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU10',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU11',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU12',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU13',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU14',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU5',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU6',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU7',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU8',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor1CIU9',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU10',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU11',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU12',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU5',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU6',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU7',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU8',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor2CIU9',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU10',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU11',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU12',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU5',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU6',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU7',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU8',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor3CIU9',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('switch', models.CharField(default=b'OFF', max_length=3, choices=[(b'ON', b'On'), (b'OFF', b'Off')])),
                ('temperature', models.FloatField()),
                ('setTemp', models.SmallIntegerField()),
                ('opMode', models.CharField(max_length=2, choices=[(b'CL', b'\xeb\x83\x89\xeb\xb0\xa9'), (b'HT', b'\xeb\x82\x9c\xeb\xb0\xa9'), (b'AR', b'\xec\x86\xa1\xed\x92\x8d'), (b'AT', b'\xec\x9e\x90\xeb\x8f\x99')])),
                ('airFlow', models.CharField(max_length=2, choices=[(b'WK', b'\xec\x95\xbd\xed\x92\x8d'), (b'NM', b'\xec\xa4\x91\xed\x92\x8d'), (b'ST', b'\xea\xb0\x95\xed\x92\x8d')])),
                ('state', models.CharField(max_length=2, choices=[(b'ER', b'\xec\x97\x90\xeb\x9f\xac'), (b'NM', b'\xec\xa0\x95\xec\x83\x81')])),
            ],
        ),
    ]
