# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_ceilingindoorunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeilingIndoorUnit',
        ),
        migrations.AddField(
            model_name='floor1ciu1',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu10',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu11',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu12',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu13',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu14',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu2',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu3',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu4',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu5',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu6',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu7',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu8',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu9',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor2ciu1',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu10',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu11',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu12',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu2',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu3',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu4',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu5',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu6',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu7',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu8',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu9',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor3ciu1',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu10',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu11',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu12',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu2',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu3',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu4',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu5',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu6',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu7',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu8',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu9',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
    ]
