from django.contrib import admin

from models import *

# Logger
admin.site.register(OperationSwitchControl)
admin.site.register(OperationLogger)
admin.site.register(DeepwellPump1Logger)
admin.site.register(DeepwellPump2Logger)
admin.site.register(DeepwellPump3Logger)
admin.site.register(DeepwellPump4Logger)
admin.site.register(CirculatingPumpLogger)
admin.site.register(DWPFlowmeterLogger) 
admin.site.register(CPFlowmeterLogger) 
admin.site.register(TemperatureLogger)
admin.site.register(TempHEIn1Logger)
admin.site.register(TempHEIn2Logger)
admin.site.register(TempHPIn1Logger)
admin.site.register(TempHPIn2Logger)
admin.site.register(TempHPIn3Logger)
admin.site.register(TempHPIn4Logger)
admin.site.register(TempHPIn5Logger)
admin.site.register(TempHPIn6Logger)
admin.site.register(TempHEOut1Logger)
admin.site.register(TempHEOut2Logger)
admin.site.register(TempHPOut1Logger)
admin.site.register(TempHPOut2Logger)
admin.site.register(TempHPOut3Logger)
admin.site.register(TempHPOut4Logger)
admin.site.register(TempHPOut5Logger)
admin.site.register(TempHPOut6Logger)
admin.site.register(InverterLogger)
admin.site.register(HeatPump1Logger)
admin.site.register(HeatPump2Logger)
admin.site.register(HeatPump3Logger)
admin.site.register(HeatPump4Logger)
admin.site.register(HeatPump5Logger)
admin.site.register(HeatPump6Logger)
admin.site.register(PowerConsumptionLogger)
admin.site.register(RefrigerationTonLogger)
admin.site.register(TubeWellLogger)
# Device Info
admin.site.register(FlowmeterInfo)
admin.site.register(InverterInfo)
admin.site.register(WattHourMeterInfo)
admin.site.register(HeatExchangerInfo)
admin.site.register(HeatPumpInfo)
admin.site.register(CirculatingPumpInfo)
admin.site.register(DeepwellPumpInfo)


